version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Show Variables
          command: |
            make devops-print-variables
      # - run:
      #     name: Run Test Suite
      #     command: |
      #       make devops-test-suite || make devops-test-suite DEBUG=1
      - run:
          name: Push 'nginx' image
          command: |
            make NAME=nginx DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD \
              docker-build \
              docker-test \
              docker-login \
              docker-push
      - run:
          name: Push 'postgres' image
          command: |
            make NAME=postgres DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD \
              docker-build \
              docker-test \
              docker-login \
              docker-push
      - run:
          name: Push 'tools' image
          command: |
            make NAME=tools DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD \
              docker-build \
              docker-test \
              docker-login \
              docker-push
