version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Configure Environment
          command: |
            sudo sysctl -w vm.max_map_count=262144
      - run:
          name: Show Variables
          command: |
            make devops-print-variables
      - run:
          name: Run Test Suite
          command: |
            make devops-test-suite || make devops-test-suite DEBUG=1
      - run:
          name: Push 'elasticsearch' image
          command: |
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/elasticsearch
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/elasticsearch/CUcLDfBRSM2kIctxQbBVTM47W4w="
      - run:
          name: Push 'nginx' image
          command: |
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/nginx
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/nginx/Yig4ioTnvCL1zCIJnBTypPLR1ic="
      - run:
          name: Push 'postgres' image
          command: |
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/postgres
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/postgres/ei_kYbqtiwOtONIc5PV9_ZB-ANQ="
      - run:
          name: Push 'python-base' image
          command: |
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/python-base
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/python-base/6rhtUJFjPZD6XkzfZ7tE5o1KJp8="
      - run:
          name: Push 'tools' image
          command: |
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/tools
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/tools/D3mmi11C-dT0VlRZZv2vqimdYJ0="
