version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Configure Environment
          command: |
            sudo sysctl -w vm.max_map_count=262144
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S%z")
            echo "export BUILD_DATE=$BUILD_DATE" >> $BASH_ENV
      - run:
          name: Show Variables
          command: |
            make devops-print-variables
      - run:
          name: Push 'elasticsearch' image
          command: |
            [ true == $(make git-commit-has-changed-directory DIR=build/automation/lib/docker/image/elasticsearch) ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/elasticsearch
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/elasticsearch/CUcLDfBRSM2kIctxQbBVTM47W4w="
      - run:
          name: Push 'nginx' image
          command: |
            [ true == $(make git-commit-has-changed-directory DIR=build/automation/lib/docker/image/nginx) ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/nginx
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/nginx/Yig4ioTnvCL1zCIJnBTypPLR1ic="
      - run:
          name: Push 'node' image
          command: |
            [ true == $(make git-commit-has-changed-directory DIR=build/automation/lib/docker/image/node) ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/node
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/node/94ikQd3QKszS1_Y3eGlMcbt5iiI="
      - run:
          name: Push 'postgres' image
          command: |
            [ true == $(make git-commit-has-changed-directory DIR=build/automation/lib/docker/image/postgres) ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/postgres
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/postgres/ei_kYbqtiwOtONIc5PV9_ZB-ANQ="
      - run:
          name: Push 'python' image
          command: |
            [ true == $(make git-commit-has-changed-directory DIR=build/automation/lib/docker/image/python) ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/python
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/python/CIrtN8vL4NBjH75NnXxM7rWFAbg="
      - run:
          name: Push 'python-app' image
          command: |
            [ true == $(make git-commit-has-changed-directory DIR=build/automation/lib/docker/image/python-app) ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/python-app
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/python-app/4eMOA9iHngrFwZ0fTWlMq4KR9Kk="
      - run:
          name: Push 'tools' image
          command: |
            [ true == $(make git-commit-has-changed-directory DIR=build/automation/lib/docker/image/tools) ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/tools
            make \
              build \
              test \
              push \
              clean
            curl --request POST "https://hooks.microbadger.com/images/nhsd/tools/D3mmi11C-dT0VlRZZv2vqimdYJ0="
      - run:
          name: Run Test Suite
          command: |
            make devops-test-suite || make devops-test-suite DEBUG=1
