version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Show Variables
          command: |
            make devops-print-variables
      - run:
          name: Run Test Suite
          command: |
            make devops-test-suite || make devops-test-suite DEBUG=1
      - run:
          name: Push 'postgres' image
          command: |
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            make docker-push NAME=postgres
