version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Configure Environment
          command: |
            sudo sysctl -w vm.max_map_count=262144
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S%z")
            echo "export BUILD_DATE=$BUILD_DATE" >> $BASH_ENV
      - run:
          name: Show Configuration
          command: |
            make show-configuration

      # The 'tools' image has to be built first!
      - run:
          name: Push 'tools' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/tools) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/tools
            make \
              build \
              test \
              push \
              clean

      - run:
          name: Push 'elasticsearch' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/elasticsearch) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/elasticsearch
            make \
              build \
              test \
              push \
              clean
      - run:
          name: Push 'nginx' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/nginx) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/nginx
            make \
              build \
              test \
              push \
              clean
      - run:
          name: Push 'node' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/node) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/node
            make \
              build \
              test \
              push \
              clean
      - run:
          name: Push 'pipeline' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/pipeline) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/pipeline
            make \
              build \
              test \
              push \
              clean
      - run:
          name: Push 'postgres' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/postgres) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/postgres
            make \
              build \
              test \
              push \
              clean
      - run:
          name: Push 'python' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/python) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/python
            make \
              build \
              test \
              push \
              clean
      - run:
          name: Push 'python-app' image
          command: |
            [ $(make git-check-if-commit-changed-directory DIR=build/automation/lib/docker/image/python-app) == true ] || exit 0
            make docker-login DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD
            cd build/automation/lib/docker/image/python-app
            make \
              build \
              test \
              push \
              clean
      - run:
          name: Run Test Suite
          command: |
            make devops-test-suite || make devops-test-suite DEBUG=1
