name: 'Check Pull Request Title'
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dylanvann/check-pull-request-title@master
        with:
          pattern: '^[A-Za-z]{2,5}-([0-9]{1,5}|X{1,5}) [A-Z]|^Update automation scripts|^Update versions|^Refactor'
